### ISSUE TITLE
[Bug] 插件依赖的 Python 版本错误

### ISSUE THREAD

**Issue by Ma1nt5iner** [wyf7685/nonebot-plugin-werewolf#4]
![image](https://github.com/user-attachments/assets/31982e52-d26d-46f6-899b-bf45e0eb94f2)

**Comment by wyf7685** [comment]
插件用到的 `asyncio.timeouts` 是在 Python 3.11 新增的特性，因此插件需要使用版本 >=3.11 的 Python 解释器。

插件信息中填写的 >=3.10 是错误的，将在下一个版本中修正。
