### ISSUE TITLE
[Feature] 添加 superuser 额外权限

### ISSUE THREAD

**Issue by zgyj4532** [wyf7685/nonebot-plugin-werewolf#6]
添加superuser的权限包括但不限于强制结束游戏，重新开始游戏，更改开始游戏前配置（如7人1狼1狼王，8人1女巫1预言家1白痴无猎人等)

**Comment by wyf7685** [comment]
Todo List
====

- [ ] 强制结束游戏
- [ ] 重新开始游戏
- [ ] 更改开始游戏前配置
